### ISSUE TITLE
How to use DragAndDrop with ScrollView?

### ISSUE THREAD

**Issue by alexacz** [hellojoelhuber/swiftui-drag-and-drop#1]
How to use DragAndDrop with ScrollView?

**Comment by hellojoelhuber** [comment]
Hi alexacz,

Unfortunately, draggable objects inside one View cannot easily move to another View.
For example, an element in a ScrollView or an item in a List View cannot be dragged outside of that ScrollView or List.

This limitation goes back to the UIKit days and is not unique to SwiftUI.

I have documented this as a limitation here: https://www.joelhuber.com/software-documentation/documentation-drag-and-drop-faq/ and here: https://github.com/hellojoelhuber/drag-and-drop-todo-list

Best,
Joel T. Huber
