### ISSUE TITLE
examples can not be build

### ISSUE THREAD

**Issue by shaunthegeek** [hellojoelhuber/swiftui-drag-and-drop#2]
examples can not be build in Xcode, because there is no `Example.xcodeproj`

https://github.com/hellojoelhuber/drag-and-drop-todo-list

**Comment by hellojoelhuber** [comment]
It's standard to include .xcodeproj in the .gitignore when placing a project under source control. You don't strictly have to include .xcodeproj in .gitignore if you're working solo, but it's a requirement when working as a team.

Try following this article to see if it helps you resolve your issue: https://www.dev2qa.com/how-to-create-xcode-workspace-and-add-new-exist-project-into-it/
